//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Project/Scripts/Player/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""PlayerNormal"",
            ""id"": ""bf534a02-9b00-406f-a9e0-7ef1da826880"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""347c97c3-cafe-4d8f-80e0-fb2bf554e655"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""af220c8b-2d08-428b-80eb-9cb52dd3f8a0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchPosition"",
                    ""type"": ""Value"",
                    ""id"": ""96a944d3-8ba4-472d-a8a2-52f8f8926091"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchPress"",
                    ""type"": ""Button"",
                    ""id"": ""ee7788ef-98ff-4190-a73e-05b04d90da6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchTap"",
                    ""type"": ""Button"",
                    ""id"": ""acaf9e96-f71d-4277-945f-a35852b1d94d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem"",
                    ""type"": ""Button"",
                    ""id"": ""1ae2535a-d29f-41d8-9f98-889f74b19d86"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""d9eb56d6-555a-42d3-bef4-46ee5d033aef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PullBow"",
                    ""type"": ""Button"",
                    ""id"": ""59a9582d-c958-4eb3-868e-7e592e714307"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Motion"",
                    ""type"": ""Value"",
                    ""id"": ""9377e647-79ce-43dc-816f-5e7f40c747e4"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""978bfe49-cc26-4a3d-ab7b-7d7a29327403"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PhoneWithGamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""450b8c99-f057-4d00-9cfa-1404704b78de"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""TouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c240da98-a203-4c7c-89f2-dd0e035b8537"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""TouchPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e017ef9d-6eb3-4ed6-9664-f5e5f19cd089"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""TouchTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c605312-4bfe-4ea2-89dd-8a858371ae3f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6c29c0d-0afe-4187-826c-f760f3e9a38f"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6cd5e8d-ba04-4411-a4eb-6cc21e89986c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""PullBow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f44e341e-3216-4070-ba65-ecdd9763e882"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1246340-2b2a-4a9c-aeca-a20ca01261a6"",
                    ""path"": ""<Accelerometer>/acceleration"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""Motion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""LockCamera"",
            ""id"": ""e4c60f7b-03a6-4cb5-b593-311a37a27b5f"",
            ""actions"": [
                {
                    ""name"": ""LockCamera"",
                    ""type"": ""Button"",
                    ""id"": ""a32610c9-fb9e-4364-a2cb-9ce1600cc358"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ce2ca1f2-0138-4c12-93e8-33fe7d8e8043"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""LockCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""HoldingBomb"",
            ""id"": ""9b1b3e0d-3a15-4ff9-92fe-ef1ef960a075"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""be0cd4ce-4729-4b9a-8128-f02238d07038"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""f272954c-8c59-496a-8c21-d5b38062f496"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""1a0d578a-3e64-41c0-bf2d-39424ba1b055"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""301046e0-f63c-4431-9696-4fd420cade7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Put"",
                    ""type"": ""Button"",
                    ""id"": ""097a952b-8857-46f8-8986-5ccd9de07f2d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""3535e302-3009-494e-9855-d40940999383"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0d012767-50ed-4ecc-8a1d-84c6ff673f87"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PhoneWithGamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""041c7603-15ea-4f8b-bc73-3b3ee7b6782f"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02a741f1-4a29-48f8-b95a-34376792306e"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cade6bd-0706-4d5c-bc4c-3a140a236705"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""Put"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfc96872-7336-4bed-bf29-d01f856a1d93"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0800450-d5bb-4f67-b0ff-4c8b45d35d28"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BowPov"",
            ""id"": ""01e29dcb-286d-4513-b2f4-0965ab9cf944"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d5d7bc99-f92e-42f5-a792-399684488a9c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""1ef9c504-4a48-46da-a60e-973a7c95cd38"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ButtonShoot"",
                    ""type"": ""Button"",
                    ""id"": ""97a29a54-fae2-4064-99be-804754383397"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""42bab7bb-49d5-4925-b759-28fe221ff299"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchPosition"",
                    ""type"": ""Value"",
                    ""id"": ""da05d122-3022-4f5d-a224-8c4637cd0ef4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchPress"",
                    ""type"": ""Button"",
                    ""id"": ""37c8cb4b-9e5b-423d-be36-65f136a3e551"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bc39fb27-3e77-4d45-9515-5c0dab6e4b6e"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0610a57-6a02-4ab0-8c6d-81afa629b50b"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63f4ef87-e83b-4273-9b71-f6359ca55994"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""ButtonShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cdff6a6-4f49-4b0f-9169-50a95024b5e6"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4460aa37-08ab-42a1-91a7-8b965ccbeb3a"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""TouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76a53961-3b4b-463f-b05e-3c1aa8d5b60f"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PhoneWithGamepad"",
                    ""action"": ""TouchPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""c7dffcdf-b0ec-423e-93b1-440b9999fba2"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PhoneWithGamepad"",
            ""bindingGroup"": ""PhoneWithGamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerNormal
        m_PlayerNormal = asset.FindActionMap("PlayerNormal", throwIfNotFound: true);
        m_PlayerNormal_Move = m_PlayerNormal.FindAction("Move", throwIfNotFound: true);
        m_PlayerNormal_Rotate = m_PlayerNormal.FindAction("Rotate", throwIfNotFound: true);
        m_PlayerNormal_TouchPosition = m_PlayerNormal.FindAction("TouchPosition", throwIfNotFound: true);
        m_PlayerNormal_TouchPress = m_PlayerNormal.FindAction("TouchPress", throwIfNotFound: true);
        m_PlayerNormal_TouchTap = m_PlayerNormal.FindAction("TouchTap", throwIfNotFound: true);
        m_PlayerNormal_UseItem = m_PlayerNormal.FindAction("UseItem", throwIfNotFound: true);
        m_PlayerNormal_Jump = m_PlayerNormal.FindAction("Jump", throwIfNotFound: true);
        m_PlayerNormal_PullBow = m_PlayerNormal.FindAction("PullBow", throwIfNotFound: true);
        m_PlayerNormal_Motion = m_PlayerNormal.FindAction("Motion", throwIfNotFound: true);
        // LockCamera
        m_LockCamera = asset.FindActionMap("LockCamera", throwIfNotFound: true);
        m_LockCamera_LockCamera = m_LockCamera.FindAction("LockCamera", throwIfNotFound: true);
        // HoldingBomb
        m_HoldingBomb = asset.FindActionMap("HoldingBomb", throwIfNotFound: true);
        m_HoldingBomb_Move = m_HoldingBomb.FindAction("Move", throwIfNotFound: true);
        m_HoldingBomb_Rotate = m_HoldingBomb.FindAction("Rotate", throwIfNotFound: true);
        m_HoldingBomb_Jump = m_HoldingBomb.FindAction("Jump", throwIfNotFound: true);
        m_HoldingBomb_Throw = m_HoldingBomb.FindAction("Throw", throwIfNotFound: true);
        m_HoldingBomb_Put = m_HoldingBomb.FindAction("Put", throwIfNotFound: true);
        m_HoldingBomb_Cancel = m_HoldingBomb.FindAction("Cancel", throwIfNotFound: true);
        // BowPov
        m_BowPov = asset.FindActionMap("BowPov", throwIfNotFound: true);
        m_BowPov_Move = m_BowPov.FindAction("Move", throwIfNotFound: true);
        m_BowPov_Rotate = m_BowPov.FindAction("Rotate", throwIfNotFound: true);
        m_BowPov_ButtonShoot = m_BowPov.FindAction("ButtonShoot", throwIfNotFound: true);
        m_BowPov_Cancel = m_BowPov.FindAction("Cancel", throwIfNotFound: true);
        m_BowPov_TouchPosition = m_BowPov.FindAction("TouchPosition", throwIfNotFound: true);
        m_BowPov_TouchPress = m_BowPov.FindAction("TouchPress", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerNormal
    private readonly InputActionMap m_PlayerNormal;
    private List<IPlayerNormalActions> m_PlayerNormalActionsCallbackInterfaces = new List<IPlayerNormalActions>();
    private readonly InputAction m_PlayerNormal_Move;
    private readonly InputAction m_PlayerNormal_Rotate;
    private readonly InputAction m_PlayerNormal_TouchPosition;
    private readonly InputAction m_PlayerNormal_TouchPress;
    private readonly InputAction m_PlayerNormal_TouchTap;
    private readonly InputAction m_PlayerNormal_UseItem;
    private readonly InputAction m_PlayerNormal_Jump;
    private readonly InputAction m_PlayerNormal_PullBow;
    private readonly InputAction m_PlayerNormal_Motion;
    public struct PlayerNormalActions
    {
        private @Controls m_Wrapper;
        public PlayerNormalActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerNormal_Move;
        public InputAction @Rotate => m_Wrapper.m_PlayerNormal_Rotate;
        public InputAction @TouchPosition => m_Wrapper.m_PlayerNormal_TouchPosition;
        public InputAction @TouchPress => m_Wrapper.m_PlayerNormal_TouchPress;
        public InputAction @TouchTap => m_Wrapper.m_PlayerNormal_TouchTap;
        public InputAction @UseItem => m_Wrapper.m_PlayerNormal_UseItem;
        public InputAction @Jump => m_Wrapper.m_PlayerNormal_Jump;
        public InputAction @PullBow => m_Wrapper.m_PlayerNormal_PullBow;
        public InputAction @Motion => m_Wrapper.m_PlayerNormal_Motion;
        public InputActionMap Get() { return m_Wrapper.m_PlayerNormal; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerNormalActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerNormalActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerNormalActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerNormalActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @TouchPosition.started += instance.OnTouchPosition;
            @TouchPosition.performed += instance.OnTouchPosition;
            @TouchPosition.canceled += instance.OnTouchPosition;
            @TouchPress.started += instance.OnTouchPress;
            @TouchPress.performed += instance.OnTouchPress;
            @TouchPress.canceled += instance.OnTouchPress;
            @TouchTap.started += instance.OnTouchTap;
            @TouchTap.performed += instance.OnTouchTap;
            @TouchTap.canceled += instance.OnTouchTap;
            @UseItem.started += instance.OnUseItem;
            @UseItem.performed += instance.OnUseItem;
            @UseItem.canceled += instance.OnUseItem;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @PullBow.started += instance.OnPullBow;
            @PullBow.performed += instance.OnPullBow;
            @PullBow.canceled += instance.OnPullBow;
            @Motion.started += instance.OnMotion;
            @Motion.performed += instance.OnMotion;
            @Motion.canceled += instance.OnMotion;
        }

        private void UnregisterCallbacks(IPlayerNormalActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @TouchPosition.started -= instance.OnTouchPosition;
            @TouchPosition.performed -= instance.OnTouchPosition;
            @TouchPosition.canceled -= instance.OnTouchPosition;
            @TouchPress.started -= instance.OnTouchPress;
            @TouchPress.performed -= instance.OnTouchPress;
            @TouchPress.canceled -= instance.OnTouchPress;
            @TouchTap.started -= instance.OnTouchTap;
            @TouchTap.performed -= instance.OnTouchTap;
            @TouchTap.canceled -= instance.OnTouchTap;
            @UseItem.started -= instance.OnUseItem;
            @UseItem.performed -= instance.OnUseItem;
            @UseItem.canceled -= instance.OnUseItem;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @PullBow.started -= instance.OnPullBow;
            @PullBow.performed -= instance.OnPullBow;
            @PullBow.canceled -= instance.OnPullBow;
            @Motion.started -= instance.OnMotion;
            @Motion.performed -= instance.OnMotion;
            @Motion.canceled -= instance.OnMotion;
        }

        public void RemoveCallbacks(IPlayerNormalActions instance)
        {
            if (m_Wrapper.m_PlayerNormalActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerNormalActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerNormalActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerNormalActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerNormalActions @PlayerNormal => new PlayerNormalActions(this);

    // LockCamera
    private readonly InputActionMap m_LockCamera;
    private List<ILockCameraActions> m_LockCameraActionsCallbackInterfaces = new List<ILockCameraActions>();
    private readonly InputAction m_LockCamera_LockCamera;
    public struct LockCameraActions
    {
        private @Controls m_Wrapper;
        public LockCameraActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @LockCamera => m_Wrapper.m_LockCamera_LockCamera;
        public InputActionMap Get() { return m_Wrapper.m_LockCamera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LockCameraActions set) { return set.Get(); }
        public void AddCallbacks(ILockCameraActions instance)
        {
            if (instance == null || m_Wrapper.m_LockCameraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LockCameraActionsCallbackInterfaces.Add(instance);
            @LockCamera.started += instance.OnLockCamera;
            @LockCamera.performed += instance.OnLockCamera;
            @LockCamera.canceled += instance.OnLockCamera;
        }

        private void UnregisterCallbacks(ILockCameraActions instance)
        {
            @LockCamera.started -= instance.OnLockCamera;
            @LockCamera.performed -= instance.OnLockCamera;
            @LockCamera.canceled -= instance.OnLockCamera;
        }

        public void RemoveCallbacks(ILockCameraActions instance)
        {
            if (m_Wrapper.m_LockCameraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILockCameraActions instance)
        {
            foreach (var item in m_Wrapper.m_LockCameraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LockCameraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LockCameraActions @LockCamera => new LockCameraActions(this);

    // HoldingBomb
    private readonly InputActionMap m_HoldingBomb;
    private List<IHoldingBombActions> m_HoldingBombActionsCallbackInterfaces = new List<IHoldingBombActions>();
    private readonly InputAction m_HoldingBomb_Move;
    private readonly InputAction m_HoldingBomb_Rotate;
    private readonly InputAction m_HoldingBomb_Jump;
    private readonly InputAction m_HoldingBomb_Throw;
    private readonly InputAction m_HoldingBomb_Put;
    private readonly InputAction m_HoldingBomb_Cancel;
    public struct HoldingBombActions
    {
        private @Controls m_Wrapper;
        public HoldingBombActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_HoldingBomb_Move;
        public InputAction @Rotate => m_Wrapper.m_HoldingBomb_Rotate;
        public InputAction @Jump => m_Wrapper.m_HoldingBomb_Jump;
        public InputAction @Throw => m_Wrapper.m_HoldingBomb_Throw;
        public InputAction @Put => m_Wrapper.m_HoldingBomb_Put;
        public InputAction @Cancel => m_Wrapper.m_HoldingBomb_Cancel;
        public InputActionMap Get() { return m_Wrapper.m_HoldingBomb; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HoldingBombActions set) { return set.Get(); }
        public void AddCallbacks(IHoldingBombActions instance)
        {
            if (instance == null || m_Wrapper.m_HoldingBombActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HoldingBombActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Throw.started += instance.OnThrow;
            @Throw.performed += instance.OnThrow;
            @Throw.canceled += instance.OnThrow;
            @Put.started += instance.OnPut;
            @Put.performed += instance.OnPut;
            @Put.canceled += instance.OnPut;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
        }

        private void UnregisterCallbacks(IHoldingBombActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Throw.started -= instance.OnThrow;
            @Throw.performed -= instance.OnThrow;
            @Throw.canceled -= instance.OnThrow;
            @Put.started -= instance.OnPut;
            @Put.performed -= instance.OnPut;
            @Put.canceled -= instance.OnPut;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
        }

        public void RemoveCallbacks(IHoldingBombActions instance)
        {
            if (m_Wrapper.m_HoldingBombActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHoldingBombActions instance)
        {
            foreach (var item in m_Wrapper.m_HoldingBombActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HoldingBombActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HoldingBombActions @HoldingBomb => new HoldingBombActions(this);

    // BowPov
    private readonly InputActionMap m_BowPov;
    private List<IBowPovActions> m_BowPovActionsCallbackInterfaces = new List<IBowPovActions>();
    private readonly InputAction m_BowPov_Move;
    private readonly InputAction m_BowPov_Rotate;
    private readonly InputAction m_BowPov_ButtonShoot;
    private readonly InputAction m_BowPov_Cancel;
    private readonly InputAction m_BowPov_TouchPosition;
    private readonly InputAction m_BowPov_TouchPress;
    public struct BowPovActions
    {
        private @Controls m_Wrapper;
        public BowPovActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_BowPov_Move;
        public InputAction @Rotate => m_Wrapper.m_BowPov_Rotate;
        public InputAction @ButtonShoot => m_Wrapper.m_BowPov_ButtonShoot;
        public InputAction @Cancel => m_Wrapper.m_BowPov_Cancel;
        public InputAction @TouchPosition => m_Wrapper.m_BowPov_TouchPosition;
        public InputAction @TouchPress => m_Wrapper.m_BowPov_TouchPress;
        public InputActionMap Get() { return m_Wrapper.m_BowPov; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BowPovActions set) { return set.Get(); }
        public void AddCallbacks(IBowPovActions instance)
        {
            if (instance == null || m_Wrapper.m_BowPovActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BowPovActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @ButtonShoot.started += instance.OnButtonShoot;
            @ButtonShoot.performed += instance.OnButtonShoot;
            @ButtonShoot.canceled += instance.OnButtonShoot;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @TouchPosition.started += instance.OnTouchPosition;
            @TouchPosition.performed += instance.OnTouchPosition;
            @TouchPosition.canceled += instance.OnTouchPosition;
            @TouchPress.started += instance.OnTouchPress;
            @TouchPress.performed += instance.OnTouchPress;
            @TouchPress.canceled += instance.OnTouchPress;
        }

        private void UnregisterCallbacks(IBowPovActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @ButtonShoot.started -= instance.OnButtonShoot;
            @ButtonShoot.performed -= instance.OnButtonShoot;
            @ButtonShoot.canceled -= instance.OnButtonShoot;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @TouchPosition.started -= instance.OnTouchPosition;
            @TouchPosition.performed -= instance.OnTouchPosition;
            @TouchPosition.canceled -= instance.OnTouchPosition;
            @TouchPress.started -= instance.OnTouchPress;
            @TouchPress.performed -= instance.OnTouchPress;
            @TouchPress.canceled -= instance.OnTouchPress;
        }

        public void RemoveCallbacks(IBowPovActions instance)
        {
            if (m_Wrapper.m_BowPovActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBowPovActions instance)
        {
            foreach (var item in m_Wrapper.m_BowPovActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BowPovActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BowPovActions @BowPov => new BowPovActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    public struct UIActions
    {
        private @Controls m_Wrapper;
        public UIActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_PhoneWithGamepadSchemeIndex = -1;
    public InputControlScheme PhoneWithGamepadScheme
    {
        get
        {
            if (m_PhoneWithGamepadSchemeIndex == -1) m_PhoneWithGamepadSchemeIndex = asset.FindControlSchemeIndex("PhoneWithGamepad");
            return asset.controlSchemes[m_PhoneWithGamepadSchemeIndex];
        }
    }
    public interface IPlayerNormalActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnTouchPosition(InputAction.CallbackContext context);
        void OnTouchPress(InputAction.CallbackContext context);
        void OnTouchTap(InputAction.CallbackContext context);
        void OnUseItem(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnPullBow(InputAction.CallbackContext context);
        void OnMotion(InputAction.CallbackContext context);
    }
    public interface ILockCameraActions
    {
        void OnLockCamera(InputAction.CallbackContext context);
    }
    public interface IHoldingBombActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnThrow(InputAction.CallbackContext context);
        void OnPut(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
    }
    public interface IBowPovActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnButtonShoot(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnTouchPosition(InputAction.CallbackContext context);
        void OnTouchPress(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
    }
}
